package com.feiying.erp.datasource.entities;

public class App {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feiying_app.Id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feiying_app.Number
     *
     * @mbggenerated
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feiying_app.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feiying_app.Type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feiying_app.Icon
     *
     * @mbggenerated
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feiying_app.URL
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feiying_app.Width
     *
     * @mbggenerated
     */
    private String width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feiying_app.Height
     *
     * @mbggenerated
     */
    private String height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feiying_app.ReSize
     *
     * @mbggenerated
     */
    private Boolean resize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feiying_app.OpenMax
     *
     * @mbggenerated
     */
    private Boolean openmax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feiying_app.Flash
     *
     * @mbggenerated
     */
    private Boolean flash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feiying_app.ZL
     *
     * @mbggenerated
     */
    private String zl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feiying_app.Sort
     *
     * @mbggenerated
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feiying_app.Remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feiying_app.Enabled
     *
     * @mbggenerated
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feiying_app.delete_Flag
     *
     * @mbggenerated
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feiying_app.Id
     *
     * @return the value of feiying_app.Id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feiying_app.Id
     *
     * @param id the value for feiying_app.Id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feiying_app.Number
     *
     * @return the value of feiying_app.Number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feiying_app.Number
     *
     * @param number the value for feiying_app.Number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feiying_app.Name
     *
     * @return the value of feiying_app.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feiying_app.Name
     *
     * @param name the value for feiying_app.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feiying_app.Type
     *
     * @return the value of feiying_app.Type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feiying_app.Type
     *
     * @param type the value for feiying_app.Type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feiying_app.Icon
     *
     * @return the value of feiying_app.Icon
     *
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feiying_app.Icon
     *
     * @param icon the value for feiying_app.Icon
     *
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feiying_app.URL
     *
     * @return the value of feiying_app.URL
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feiying_app.URL
     *
     * @param url the value for feiying_app.URL
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feiying_app.Width
     *
     * @return the value of feiying_app.Width
     *
     * @mbggenerated
     */
    public String getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feiying_app.Width
     *
     * @param width the value for feiying_app.Width
     *
     * @mbggenerated
     */
    public void setWidth(String width) {
        this.width = width == null ? null : width.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feiying_app.Height
     *
     * @return the value of feiying_app.Height
     *
     * @mbggenerated
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feiying_app.Height
     *
     * @param height the value for feiying_app.Height
     *
     * @mbggenerated
     */
    public void setHeight(String height) {
        this.height = height == null ? null : height.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feiying_app.ReSize
     *
     * @return the value of feiying_app.ReSize
     *
     * @mbggenerated
     */
    public Boolean getResize() {
        return resize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feiying_app.ReSize
     *
     * @param resize the value for feiying_app.ReSize
     *
     * @mbggenerated
     */
    public void setResize(Boolean resize) {
        this.resize = resize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feiying_app.OpenMax
     *
     * @return the value of feiying_app.OpenMax
     *
     * @mbggenerated
     */
    public Boolean getOpenmax() {
        return openmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feiying_app.OpenMax
     *
     * @param openmax the value for feiying_app.OpenMax
     *
     * @mbggenerated
     */
    public void setOpenmax(Boolean openmax) {
        this.openmax = openmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feiying_app.Flash
     *
     * @return the value of feiying_app.Flash
     *
     * @mbggenerated
     */
    public Boolean getFlash() {
        return flash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feiying_app.Flash
     *
     * @param flash the value for feiying_app.Flash
     *
     * @mbggenerated
     */
    public void setFlash(Boolean flash) {
        this.flash = flash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feiying_app.ZL
     *
     * @return the value of feiying_app.ZL
     *
     * @mbggenerated
     */
    public String getZl() {
        return zl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feiying_app.ZL
     *
     * @param zl the value for feiying_app.ZL
     *
     * @mbggenerated
     */
    public void setZl(String zl) {
        this.zl = zl == null ? null : zl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feiying_app.Sort
     *
     * @return the value of feiying_app.Sort
     *
     * @mbggenerated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feiying_app.Sort
     *
     * @param sort the value for feiying_app.Sort
     *
     * @mbggenerated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feiying_app.Remark
     *
     * @return the value of feiying_app.Remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feiying_app.Remark
     *
     * @param remark the value for feiying_app.Remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feiying_app.Enabled
     *
     * @return the value of feiying_app.Enabled
     *
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feiying_app.Enabled
     *
     * @param enabled the value for feiying_app.Enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feiying_app.delete_Flag
     *
     * @return the value of feiying_app.delete_Flag
     *
     * @mbggenerated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feiying_app.delete_Flag
     *
     * @param deleteFlag the value for feiying_app.delete_Flag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }
}